remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Documentación

nombres: Andrés Camilo Quintana Montoya
submodulo: Lógica de Programación
periodo: 2023-2
url_foto: https://firebasestorage.googleapis.com/v0/b/foto-de-git.appspot.com/o/WhatsApp%20Image%202023-09-13%20at%2017.48.29.jpeg?alt=media&token=637e40d1-886a-4bf7-88a5-629811725dd6

